name: Tests and Coverage

on: [ push ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies with Conda
        run: |
          # conda install -c defaults -c conda-forge numpy networkx ase pytest codecov pytest-cov
          conda env update --file devtools/conda-envs/github_env.yaml --name base

          # Build and install package
          python setup.py develop --no-deps

      - name: Test with pytest - coverage
        run: |
          pytest -v --cov=geometric  geometric/tests/

          # Run a Psi4 command line test if possible
          cd examples/water2_psi4
          coverage run `which geometric-optimize` --engine psi4 water2.psi4in
          cd ../..

      - name: Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)